[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.12.3", features = ["codegen", "prost"] }
prost = "0.13.4"

[build-dependencies]
tonic-build = "0.12.3"

